### ISSUE TITLE
Trim Path issue

### ISSUE THREAD

**Issue by TomHoenderdos** [bodymovin/bodymovin#206]
As I said in #197 I am having troubles with a Trim Path that is not showing correctly. Hopefully you can find the problem :smiley:. I have included a Zip file with AEP and demo html! 
I'm running bodymovin 4.4.27

What I expect:
![trim path no problem](https://cloud.githubusercontent.com/assets/1308106/21314049/3cfa71ae-c5f5-11e6-8bb4-b4f4f3159980.png)

What I get:
![trim path error](https://cloud.githubusercontent.com/assets/1308106/21314054/40d34b8e-c5f5-11e6-816e-09a371f82793.png)

So for some reason the beginning and end of the path is not connecting in the HTML version of the animation. It looks like a flooring issues where a floating number is floored and the x, y positions are stretched out too far which makes them not render at the correct location.. But i'm just guessing here ;)!

Zip File (including AEP + demo.html)
[trim_path_issue.zip](https://github.com/bodymovin/bodymovin/files/661092/trim_path_issue.zip)

**Comment by bodymovin** [comment]
fixed on v.4.4.28

**Comment by wuebkers** [comment]
I am still having this issue, is there something I can do about this in my AE file? Here is a codepen:

https://codepen.io/skytest/project/editor/XgpJbn

**Comment by bodymovin** [comment]
@wuebkers hi, can you share the aep?

**Comment by wuebkers** [comment]
https://www.dropbox.com/s/360qpyiw8bit98q/BodymovinTest.aep?dl=0

Here is the AE file that I am working with!

**Comment by bodymovin** [comment]
@wuebkers Found the issue. I'll fix it on the next upload.
It's related to trimming exactly at the position of one of the shape nodes.
Meanwhile, if you change the value to 24.9% it should work fine.

**Comment by bodymovin** [comment]
Fond out it's not as simple as that because values are not exactly the same.
And it only breaks in Chrome.
I'm closing it for now since there is a simple workaround.
