### ISSUE TITLE
playSegments function plays the whole animation

### ISSUE THREAD

**Issue by michaelgrc** [bodymovin/bodymovin#318]
Hi there,

I'd like to play only a part of frame of my animation but when I use the playSegments function, it plays all the frames.
I also checked the id and op value, and it seems correct (id = 0 & op = 111.000004521123)

Here's my code and my data.json file.

Does anyone have an idea ? Many thanks

```
var container = document.getElementById('container');
var animData = {
        container: container,
        renderer: 'svg',
        loop: false,
        prerender: false,
        autoplay: false,
        autoloadSegments: false,
        path: directory_uri+'/js/data.json'
    };
anim = bodymovin.loadAnimation(animData);
anim.playSegments([0,20],true);
```

[data (1).json.zip](https://github.com/bodymovin/bodymovin/files/844151/data.1.json.zip)

**Comment by bodymovin** [comment]
try hooking to the "DOMLoaded" event before setting the new segment, or it will be overriden once the animation data loads.
That should solve it.

**Comment by michaelgrc** [comment]
It solved it indeed !
Many thanks bodymovin master :)

**Comment by michaelgrc** [comment]
I'm sorry but I noticed it's still not working and I don't understand what the problem is.
My .js file starts with the déclaration : 

```
var container = document.getElementById('container');
var animData = {
        container: container,
        renderer: 'svg',
        loop: false,
        prerender: false,
        autoplay: false,
        autoloadSegments: false,
        path: directory_uri+'/js/data.json'
    };
anim = bodymovin.loadAnimation(animData);

```

And then I wrote this 

```
$(document).ready(function(){
        anim.playSegments([0,61],true);
});
```

But it still plays the whole animation once.
What do I miss ? 
Thank you very much :)

**Comment by michaelgrc** [comment]
I'm sorry, it finally works, I had to create an event listener like this
`anim.addEventListener('DOMLoaded',startAnimation);`

Woopsy :)

**Comment by tristanleboss** [comment]
That's 110% unintuitive! How many people ended on this page or on #398 ...

Nothing can be done to automaticaly preserve this setting once animation is loaded?

**Comment by bodymovin** [comment]
@GreenMonkeySaveEarth 
1. on web, the duration of the animation is virtually infinite. It takes AE workspace as the initial playing segment but then you can customize it to play any other part of the comp. You can even set negative values as initial and end frames. When setting progress in percentages, as it is right now, it would be a percentage of a segment [-Infinity, +Infinity]. Adding percentage as another constrain of the segment to reproduce is possible, but I'd rather not add it to the main player. It can be easily built on top of it rolling a custom ticker.
2. Answer 1 should also answer this. Converting frame to progress would mean using [-Inifinity,+Infinity], or current segment or original segment? It probably depends on each case.
3. I'd say that the best way to do it is using playSegments.

**Comment by charlesanim** [comment]
> It solved it indeed !
> Many thanks bodymovin master :)

Can you post your solution here if you don't mind? I'm having this same issue.

**Comment by mattlindsay** [comment]
What am I doing wrong?
The entire animation timeline plays. I am trying to loop the the last segment only..
My code as follows:

lottie.loadAnimation({
    container: document.getElementById('lottie'),
    renderer: 'svg',
    loop: true,
    autoplay: true,
    //autoloadSegments: false,
    path: 'data.json'
})

var anim;

anim.addEventListener('DOMLoaded',function(){anim.playSegments([0,20],[21,89], true);})

**Comment by fvonellerts** [comment]
@mattlindsay `var anim = lottie.loadAnimation(...`
