### ISSUE TITLE
Duik Character not rendering

### ISSUE THREAD

**Issue by snfisch** [bodymovin/bodymovin#451]
I've tested this character before adding Duik and they display fine. After adding Duik, however, I get a white screen in browser. I've attempted to render with hidden and guides on. Is there something else I need to do to get bodymovin to work with Duik?

[bikerBodymovin.aep.zip](https://github.com/bodymovin/bodymovin/files/1038794/bikerBodymovin.aep.zip)

**Comment by bodymovin** [comment]
fixed! I will upload it later today.

**Comment by snfisch** [comment]
Thanks for the update! Still not working for me, though. Did you get it to render?

**Comment by bodymovin** [comment]
Yes, here's the animation rendered
https://codepen.io/airnan/pen/bb0ad77773f16db55d258d4003729eac
can you share a link where it fails so I can check it out?

**Comment by snfisch** [comment]
Looks good! I've managed to replicate your codepen. I'm using the generated demo file to preview it. Is the problem that I'm testing locally with the demo?

**Comment by bodymovin** [comment]
might be.
Can you share the demo you're testing?

**Comment by ryaboshtanov** [comment]
Currently I'm working on project where I want to use Bodymovin plugin.

I've created an object (Simple shape) with a simple animation (to check if it works fine) and I want it to move with cursor or click or etc. I've seen example with Interactive Hand but nothing works for me like on that example.

1. I've created JSON from AE.
2. I've added an ID for my shape in JSON file.
3. I've successfully tried to catch position of my shape via Javascript.
4. When I'm trying to change it's position by (for example) 10px per click - nothing changes.

https://drive.google.com/file/d/0B8itcVfE1gUUd0ViUlloTFJpd1U/view?usp=sharing
